openapi: 3.1.0
info:
  title: Schedule, Task, Prayer and Notion Proxy API
  version: 1.4.0
servers:
  - url: https://chronic-janaya-seokbeom-f8bd352a.koyeb.app

paths:
  /gpt-webhook:
    post:
      operationId: submitUnifiedPayload
      summary: Submit schedule, task, prayer, auto-scheduling or report data using a unified format
      ...

  /get-notion-data:
    post:
      operationId: fetchNotionData
      summary: Notion DB에서 업무 데이터를 조회합니다. 완료된 항목 및 오래된 항목을 필터링할 수 있습니다.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                excludeStatus:
                  type: string
                  example: "✅완료"
                  description: 제외할 상태 값
                deadlineAfter:
                  type: string
                  format: date
                  example: "2025-01-16"
                  description: 이 날짜 이후 마감일만 포함
                includeFields:
                  type: array
                  items:
                    type: string
                  example: ["할일", "마감일", "예상소요시간", "우선순위", "진행상황"]
                  description: 포함할 필드 목록
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        할일:
                          type: string
                        마감일:
                          type: string
                          format: date
                        진행상황:
                          type: string
                        예상소요시간:
                          type: number
                        우선순위:
                          type: string
