openapi: 3.0.1
info:
  title: Notion Tasks API
  version: "1.0.0"
  description: API to fetch Notion task list

servers:
  - url: https://gpt-proxy-fjov.onrender.com

paths:
  /tasks:
    get:
      summary: Get tasks from Notion
      operationId: getTasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    due:
                      type: string
                    description:
                      type: string
